#!/usr/bin/env bash
#This is displaying  copying and renaming
trap interrup SIGTERM

interrup()
{
    echo "I am invincible!!!"
}

while true
do
         echo "To infinity and beyond"
         sleep 2
done
